version: "3.8"

services:
  db_chat_realtime:
    image: postgres
    container_name: db_chat_realtime
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_chat_realtime
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
